name: Lint

on: [push]

jobs:
  scala-test:
    runs-on: ubuntu-latest
    name: Scala Lint
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
      - name: Lint
        run: sbt scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'
