name: Lint

on: [push]

jobs:
  scala-lint:
    runs-on: ubuntu-latest
    name: Scala Lint
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
      - name: Lint
        run: sbt scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'

  node-lint:
    runs-on: ubuntu-latest
    name: Node Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install
        run: yarn install --frozen-lockfile --ignore-platform
      - name: Lint
        run: yarn workspace recheck lint
      - name: Type Check
        run: yarn workspace recheck typecheck
