name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-20.04
    name: Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
